# **Generating the dataset.**

In [ ]:
from random import sample
import tensorflow as tf

data = sample(range(10000000), 100000) # Generate 10000000 numbers
print(data[:10]) # Print the first few

[1533924, 914788, 7596739, 6691559, 2815703, 3667047, 7726311, 6969928, 9714912, 644751]


In [ ]:
inputs = {}
for i in range(len(data)):
  inputs.update({data[i]: 0 if data[i] % 2 != 0 else 1})

In [ ]:
import pandas as pd
df = pd.DataFrame(inputs.items(), columns=["Numbers", "Target"])

In [ ]:
df.head()

Numbers  Target
0  1533924       1
1   914788       1
2  7596739       0
3  6691559       0
4  2815703       0

In [ ]:
target = df.pop('Target')
numbers = df['Numbers']
tf.convert_to_tensor(numbers)

<tf.Tensor: shape=(100000,), dtype=int64, numpy=array([1533924,  914788, 7596739, ..., 6412921, 9256915, 3329912])>

In [ ]:
normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer.adapt(numbers)
normalizer(numbers.iloc[:10])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-1.1978403 , -1.4128308 ,  0.9074286 ,  0.5931114 , -0.75275177,
        -0.45712867,  0.95242155,  0.689773  ,  1.642949  , -1.5065992 ]],
      dtype=float32)>

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(64, input_dim=1, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(8, activation='relu'))
model.add(tf.keras.layers.Dense(4, activation='relu'))
model.add(tf.keras.layers.Dense(2, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
# Compile model
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(numbers, target, epochs=30, batch_size=64)

Epoch 1/30
1563/1563 [==============================] - 5s 2ms/step - loss: 0.5019 - accuracy: 0.4981
Epoch 2/30
1563/1563 [==============================] - 4s 2ms/step - loss: 0.5020 - accuracy: 0.4981
Epoch 3/30
1563/1563 [==============================] - 4s 3ms/step - loss: 0.5020 - accuracy: 0.4981
Epoch 4/30
1563/1563 [==============================] - 8s 5ms/step - loss: 0.5020 - accuracy: 0.4981
Epoch 5/30
1563/1563 [==============================] - 9s 5ms/step - loss: 0.5020 - accuracy: 0.4981
Epoch 6/30
1563/1563 [==============================] - 8s 5ms/step - loss: 0.5020 - accuracy: 0.4981
Epoch 7/30
1563/1563 [==============================] - 6s 4ms/step - loss: 0.5020 - accuracy: 0.4981
Epoch 8/30
1563/1563 [==============================] - 4s 2ms/step - loss: 0.5020 - accuracy: 0.4981
Epoch 9/30
1563/1563 [==============================] - 5s 3ms/step - loss: 0.5020 - accuracy: 0.4981
Epoch 10/30
1563/1563 [==============================] - 4s 2ms/step - loss: 0.502

In [ ]:
model.save("accurate.h5")